config/routes.rb
Rails.application.routes.draw do

  root to: 'tours#index'

  namespace :admin do
    resources :tours
    resources :providers
    resources :cities
  end

  resources :tours
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :tours

  mount_uploader :image, CityImageUploader
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  has_many :tours

  mount_uploader :logo, ProviderLogoUploader
end

app/models/tour.rb
class Tour < ActiveRecord::Base
  belongs_to :city
  belongs_to :provider

  mount_uploader :image, TourImageUploader
end

app/controllers/admin/cities_controller.rb
class Admin::CitiesController < AdminController
  def index
    @cities = City.order(:id)
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new city_params
    if @city.save
      redirect_to admin_cities_path
    else
      render :new
    end
  end

  def edit
    @city = City.find params[:id]
  end

  def update
    @city = City.find params[:id]

    if @city.update_attributes city_params
      redirect_to admin_cities_path
    else
      render :edit
    end
  end

  def destroy
    @city = City.find params[:id]
    @city.destroy
    redirect_to :back
  end

  private

  def city_params
    params.require(:city).permit!
  end
end

app/controllers/admin/providers_controller.rb
class Admin::ProvidersController < AdminController
  def index
    @providers = Provider.order(:id)
  end

  def new
    @provider = Provider.new
  end

  def create
    @provider = Provider.new provider_params

    if @provider.save
      redirect_to admin_providers_path
    else
      render :new
    end
  end

  def edit
    @provider = Provider.find params[:id]
  end

  def update
    @provider = Provider.find params[:id]

    if @provider.update_attributes provider_params
      redirect_to admin_providers_path
    else
      render :edit
    end
  end

  def destroy
    @provider = Provider.find params[:id]
    redirect_to :back
  end

  private

  def provider_params
    params.require(:provider).permit!
  end
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < AdminController
  def index
    @tours = Tour.order(:id)
  end

  def new
    @tour = Tour.new
  end

  def create
    @tour = Tour.new tour_params

    if @tour.save
      redirect_to admin_tours_path
    else
      render :new
    end
  end

  def edit
    @tour = Tour.find params[:id]
  end

  def update
    @tour = Tour.find params[:id]

    if @tour.update_attributes tour_params
      redirect_to admin_tours_path
    else
      render :edit
    end
  end

  def destroy
    @tour = Tour.find params[:id]
    redirect_to :back
  end

  private

  def tour_params
    params.require(:tour).permit!
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController

  layout :resolve_layout

  def index
    @tours = Tour.order(:id)
    @cities = City.order(:id)
  end

  def show
    @tour = Tour.find params[:id]
  end

  private

  def resolve_layout
    case action_name

    when "index"
      "main_page"
    else
      "application"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/cities/_form.html.haml
= simple_form_for city, url: url do |f|
  = f.input :name
  = image_tag city.image_url(:thumb) if city.image?
  = f.input :image
  = f.submit 'Готово', class: [:btn, 'btn-lg', 'btn-success']

app/views/admin/cities/edit.html.haml
%legend
  Изменить город

.row
  .col-md-8
    = render partial: 'admin/cities/form', locals: {city: @city, url: admin_city_path(@city)}

app/views/admin/cities/index.html.haml
%legend
  Города

  %a.btn{href: new_admin_city_path, style: 'float: right'} Добавить


%table.table.table-striped
  %thead
    %tr
      %td
        Название
      %td
        Количество туров
      %td
        = '...'

  %tbody
    - @cities.each do |city|
      %tr
        %td
          = city.name
        %td
          = city.tours_count.to_s

        %td
          = link_to 'редактировать', edit_admin_city_path(city)
          = link_to 'удалить', admin_city_path(city), method: :delete, confirm: 'Удалить город?'

app/views/admin/cities/new.html.haml
%legend
  Добавить город

.row
  .col-md-8
    = render partial: 'admin/cities/form', locals: {city: @city, url: admin_cities_path}

app/views/admin/providers/_form.html.haml
= simple_form_for provider, url: url do |f|
  = f.input :name
  -#= image_tag article.image_url(:thumb) if article.image?
  -#= f.input :image
  = f.submit 'Готово', class: [:btn, 'btn-lg', 'btn-success']

app/views/admin/providers/edit.html.haml
%legend
  Изменить провайдера

.row
  .col-md-8
    = render partial: 'admin/providers/form', locals: {provider: @provider, url: admin_provider_path(@provider)}

app/views/admin/providers/index.html.haml
%legend
  Провайдеры

  %a.btn{href: new_admin_provider_path, style: 'float: right'} Добавить


%table.table.table-striped
  %thead
    %tr
      %td
        Название
      %td
        Количество туров
      %td
        = '...'

  %tbody
    - @providers.each do |provider|
      %tr
        %td
          = provider.name
        %td
          = provider.tours_count.to_s

        %td
          = link_to 'редактировать', edit_admin_provider_path(provider)
          = link_to 'удалить', admin_provider_path(provider), method: :delete, confirm: 'Удалить провайдера?'

app/views/admin/providers/new.html.haml
%legend
  Добавить провайдера

.row
  .col-md-8
    = render partial: 'admin/providers/form', locals: {provider: @provider, url: admin_providers_path}

app/views/admin/tours/_form.html.haml
= simple_form_for tour, url: url do |f|
  = f.input :name
  = f.association :city
  = f.association :provider
  = image_tag tour.image_url(:thumb) if tour.image?
  = f.input :image
  = f.input :annotation
  = f.input :description
  = f.input :start_date
  = f.input :finish_date
  = f.input :price
  
  = f.submit 'Готово', class: [:btn, 'btn-lg', 'btn-success']

app/views/admin/tours/edit.html.haml
%legend
  Изменить данные тура

.row
  .col-md-8
    = render partial: 'admin/tours/form', locals: {tour: @tour, url: admin_tour_path(@tour)}

app/views/admin/tours/index.html.haml
%legend
  Туры

  %a.btn{href: new_admin_tour_path, style: 'float: right'} Добавить


%table.table.table-striped
  %thead
    %tr
      %td
        Название
      %td
        Город
      %td
        Провайдер
      %td
        = '...'

  %tbody
    - @tours.each do |tour|
      %tr
        %td
          = tour.name
        %td
          = tour.city.name
        %td
          = tour.provider.name

        %td
          = link_to 'редактировать', edit_admin_tour_path(tour)
          = link_to 'удалить', admin_tour_path(tour), method: :delete, confirm: 'Удалить тур?'

app/views/admin/tours/new.html.haml
%legend
  Добавить тур

.row
  .col-md-8
    = render partial: 'admin/tours/form', locals: {tour: @tour, url: admin_tours_path}

app/views/application/index.html.haml
.intro
  .topbar
    .wrapper
      .logo

      %ul.nav
        %li
          = link_to 'Все города', root_path
        %li
          = link_to 'О проекте', root_path
        %li
          = link_to 'Партнерам', root_path
        %li
          = link_to 'Войти', root_path, class: 'ghost-signin'

  .intro-title
    Экскурсии и туры по городам России

  .intro-subtitle
    Путешествуй по родной стране, узнавай новые места,
    %br
    получай яркие впечатления

  .about-project
    Подробнее о проекте


%section
  .wrapper
    .title
      Популярные города

    .cities.clearfix
      - @cities.each do |city|
        = render partial: 'cities/city', locals: {city: city}

%section.striped
  .wrapper
    .title
      Популярные экскурсии

    .tours.clearfix
      - @tours.each do |tour|
        = render partial: 'tours/tour', locals: {tour: tour}


#footer
  .wrapper
    .copy
      &copy;
      Колобок.travel
    %ul.nav
      %li
        = link_to 'Все города', root_path
      %li
        = link_to 'О проекте', root_path
      %li
        = link_to 'Партнерам', root_path

app/views/cities/_city.html.haml
.city
  = image_tag city.image_url(:thumb)
  .overlay
    = link_to city.name, root_path, class: :name
    .number 17 экскурсий

app/views/layouts/_admin_topbar.html.haml
%nav.navbar.navbar-default{role: :navigation}
  .container
    .navbar-header
      %button.navbar-toggle{type: :button, 'data-toggle' => 'collapse'}
        %span.sr-only
          Toggle Navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: admin_tours_path}
        ADMIN

    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li{class: params[:controller] == 'admin/tours' ? 'active' : ''}
          %a{href: admin_tours_path}
            Туры

        %li{class: params[:controller] == 'admin/cities' ? 'active' : ''}
          %a{href: admin_cities_path}
            Города


        %li{class: params[:controller] == 'admin/providers' ? 'active' : ''}
          %a{href: admin_providers_path}
            Провайдеры
            

app/views/layouts/admin.html.haml
!!! 5
%html
  %head
    = csrf_meta_tags
    = stylesheet_link_tag    'admin', :media => 'all'
    = javascript_include_tag 'admin'


    %title
      Панель управления

  %body
    = render partial: 'layouts/admin_topbar'

    .container

      -#%ol.breadcrumb
      -#  = render_breadcrumbs separator: ' / ', class: :li

      = yield

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    = csrf_meta_tags
    = stylesheet_link_tag    'application', :media => 'all'
    = javascript_include_tag 'application'


    %title
      Колобок трэвел

  %body
    .topbar
      .wrapper
        .logo

        %ul.nav
          %li
            = link_to 'Все города', root_path
          %li
            = link_to 'О проекте', root_path
          %li
            = link_to 'Партнерам', root_path
          %li
            = link_to 'Войти', root_path, class: 'ghost-signin'

    = yield

    #footer
      .wrapper
        .copy
          &copy;
          Колобок.travel
        %ul.nav
          %li
            = link_to 'Все города', root_path
          %li
            = link_to 'О проекте', root_path
          %li
            = link_to 'Партнерам', root_path

app/views/layouts/main_page.html.haml
!!! 5
%html
  %head
    = csrf_meta_tags
    = stylesheet_link_tag    'application', :media => 'all'
    = javascript_include_tag 'application'


    %title
      Колобок трэвел

  %body
    = yield

app/views/tours/_tour.html.haml
.tour
  = image_tag tour.image_url(:thumb)
  .params.clearfix
    .city
      = tour.city.name
    .duration
      3 часа

  .name
    = link_to tour.name, tour_path(tour)

  .desc
    = link_to tour.annotation, tour_path(tour)

  .price
    %span.value
      = tour.price.to_s
      рублей
    за человека

app/views/tours/index.html.haml
.intro
  .topbar
    .wrapper
      .logo

      %ul.nav
        %li
          = link_to 'Все города', root_path
        %li
          = link_to 'О проекте', root_path
        %li
          = link_to 'Партнерам', root_path
        %li
          = link_to 'Войти', root_path, class: 'ghost-signin'

  .intro-title
    Экскурсии и туры по городам России

  .intro-subtitle
    Путешествуй по родной стране, узнавай новые места,
    %br
    получай яркие впечатления

  .about-project
    Подробнее о проекте


%section
  .wrapper
    .title
      Популярные города

    .cities.clearfix
      - @cities.each do |city|
        = render partial: 'cities/city', locals: {city: city}

%section.striped
  .wrapper
    .title
      Популярные экскурсии

    .tours.clearfix
      - @tours.each do |tour|
        = render partial: 'tours/tour', locals: {tour: tour}


#footer
  .wrapper
    .copy
      &copy;
      Колобок.travel
    %ul.nav
      %li
        = link_to 'Все города', root_path
      %li
        = link_to 'О проекте', root_path
      %li
        = link_to 'Партнерам', root_path

app/views/tours/show.html.haml
#tour
  .wrapper
    .name
      = @tour.name
    .details.clearfix

      .content

        .gallery
          .image
          .previews.clearfix
            .preview
            .preview
            .preview
            .preview

        .about
          .title
            Описание экскурсии
          .text
            = @tour.description

        .button
          Забронировать экскурсию

      .sidebar
        .block
          .params
            Продолжительность:
            %strong
              3 часа

            %br

            Тип экскурсии: 
            %strong
              Автобусная

            %br

            Для какой компании:
            %strong
              до 40 человек

        .block.tall
          .price
            2 900 Р
          за человека

          .button
            Забронировать

        .block.tall


          .avatar

          .provider-name 
            Елена Румянцева

          .provider-about 
            официальный представитель
            компании «Туры по Волге» 



          .button
            Задать вопрос гиду



        